name: Changesets Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup@v2
        with:
          version: 16.x

      - name: Install Dependencies
        run: npm ci

      - name: Changesets Magic
        id: changesets
        uses: changesets/action@main
        with:
          publish: npm run release