name: Package Testing
on: pull_request

jobs:
  danger:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        node: [10, 12, 14, 16]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup@v2
        with:
          version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm ci

      - name: Package Testing
        run: npm test